### ISSUE TITLE
Vertex Shader re-use with instances.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#106]
Section 8.5.1, Vertex Shader Execution states that the implementation is allowed to reuse any vertex shader's outputs if the vertex index is the same. But no mention is made of the _instance_ index. For it to produce the same outputs, the VS must have the same vertex and instance indices, correct?

The section should be adjusted to make this more clear.

**Comment by janharaldfredriksen-arm** [comment]
> For it to produce the same outputs, the VS must have the same vertex and instance indices, correct?

Correct.

I read the references to "same index value" in that paragraph as non-exhaustive examples, but it could perhaps be clarified. You're looking for something like: "vertex shader may be invoked only once _per instance_"?

**Comment by NicolBolas** [comment]
The description needs to be exhaustive. That is what a specification is for, after all.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.17 spec update.

**Comment by NicolBolas** [comment]
That didn't fix the problem. This is the new wording:

> If the same vertex is specified multiple times in a draw command (e.g. by including the same index value multiple times in an index buffer) the implementation may reuse the results of vertex shading if it can statically determine that the vertex shader invocations will produce identical results.

It remains unclear if "same vertex" includes the instance. A simple statement saying that "same vertex" means the same vertex index and same instance would be sufficient.

**Comment by NicolBolas** [comment]
The 1.0.27 wording remains unclear, so this issue was never fully fixed.

I would suggest changing the first part to read:

> If a vertex has the same index and instance multiple times in a draw command...
