### ISSUE TITLE
Clarify vkCmdCopyImage to compressed formats

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-Docs#1637]
The spec says for vkCmdCopyImage:

> When copying from an uncompressed image to a compressed image the image texel dimensions written to the compressed image will be the source extent multiplied by the compressed texel block dimensions. 

Then it says:

> the extent must be a multiple of the compressed texel block dimension. There is one exception to this rule which is required to handle compressed images created with dimensions that are not a multiple of the compressed texel block dimensions: if the srcImage is compressed, then: If extent.width is not a multiple of the compressed texel block width, then (extent.width + srcOffset.x) must equal the image subresource width.

So extent.width must be a multiple of the compressed texel block width, even though texel dimensions written will be multiplied by it?

Or does extent.width here already include the multiplication by texel dimensions, in which case I don't see how it can ever come to this exception.

**Comment by sfricke-samsung** [comment]
This has been asked both in https://github.com/KhronosGroup/Vulkan-Docs/issues/593 and https://github.com/KhronosGroup/Vulkan-Docs/issues/1005

In my other format efforts, I am currently also looking into this, but wanted to tag the other issues as this might actually be a duplicate (but should actually be solved!)

**Comment by spencer-lunarg** [comment]
this was addressed in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5369 ([1.3.227](https://github.com/KhronosGroup/Vulkan-Docs/commit/09d120580acb942d9cc3a96c863815a05990893c))

and now reads as

![image](https://github.com/user-attachments/assets/62aa12a6-0f74-457b-a554-2de2537c5afb)

**Comment by llyzs** [comment]
I am still having issues when copying from uncompressed format to compressed format, with the above change. Let's say I have the following simplified case:

srcImage: VK_FORMAT_R32G32B32A32_UINT, 2x2, 2 mip-levels (mip0:2x2, mip1:1x1)
dstImage: VK_FORMAT_BC6H_SFLOAT_BLOCK, 8x8, 4 mip-levels (mip0:8x8, mip1:4x4, mip2:2x2, mip3:1x1)

I perform the following copies to update all mip levels of the dstImage:
1. srcImage mip(0) region(2x2) -> dstImage mip(0)
2. srcImage mip(1) region(1x1) -> dstImage mip(1)
3. srcImage mip(1) region(1x1) -> dstImage mip(2)
4. srcImage mip(1) region(1x1) -> dstImage mip(3)

The first two cases are valid - in the region(2x2) and (1x1) are scaled to (8x8) and (4x4) according to the block size of the dstImage format, and match the dstImage size at corresponding mip level.

The 3 and 4 cases does not work, because the region would still scale to (4x4) and it exceeds the size of the dstImage at mip(2) and mip(3). However, there is no way to specify a source region that would scale to a region smaller than 4x4. The copies should be valid, because the smallest mips still hold 4x4 pixel block, but the validation complains as following:

```
vkCmdCopyImage(): pRegions[0].dstOffset.x (0) + extent (4) exceeds miplevel 2 width (2).
The Vulkan spec states: For each element of pRegions, dstOffset.x and (extent.width + dstOffset.x) must both be greater than or equal to 0 and less than or equal to the width of the specified dstSubresource of dstImage (https://vulkan.lunarg.com/doc/view/1.4.313.0/linux/antora/spec/latest/chapters/copies.html#VUID-vkCmdCopyImage-dstOffset-00150)

```

**Comment by spencer-lunarg** [comment]
@llyzs thanks for raising this, so there has been a lot of re-work/fixing to the copy image code and this seems like it was just part of the VVL bug we fixed

I added a test to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10527 to confirm VVL should **not** be reporting any errors now! (with the 1.4.321 SDK)

Closing this issue and happy to address any image copies in a new fresh issue if they still occur!
