### ISSUE TITLE
Broken links in HTML Specification

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#183]
There are many broken links in the HTML version of the Specification. E.g. the _memory accesses_ link in ch. 2.2.1. leads nowhere.

The identification sign to easily find this is, that the links have `href="#"`.

**Comment by oddhack** [comment]
Urgh. There's nothing obviously wrong with the asciidoc source so we must not understand something about links. This is going to be tedious and slow to fix unless we can identify some sort of pattern in the failing links.

**Comment by krOoze** [comment]
Well, I found SOME of the patterns:
1) The verbose make complains about what I think might be exhaustive list (we shall see after fixes) of the culprits for even easier identification.

2) The [[x]] bookmark is before something it doesn't like to bind to (not before paragraf). E.g. in the `synchronization-access-flags` case, it is before some ugly include with lots of macros.

3) It simply does not exist (or have been renamed). E.g. `features-sparseproperties`

4) It is an object handle but is linked as slink (which I assume is link to an struct definition). E.g. VkInstance, VkDevice, VkImage links.

5) It is an elink to XxxFlags, which does not exist (only XxxFlagBits does). E.g. VkColorComponentFlags links.

**Comment by oddhack** [comment]
Thanks! I think I've worked through most of these internally now and will try to push it out as part of this week's updates, so suggest that you don't submit a PR on github.

**Comment by oddhack** [comment]
This should be fixed in the 1.0.11 spec update.

**Comment by krOoze** [comment]
Good work, but not so fast. Links to extensions Objects are still broken (e.g. VkSwapchainKHR).
