### ISSUE TITLE
[WSI][Editing] Minor formating issues relating to WSI

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#239]
1) In chapter 29.6. WSI Swapchain, there is a bad Unicode arrow ⇐ instead of ≤ :
>  can always succeed if a ⇐ n - m

2) In vk.xml before extensions section, there is a comment saying "none yet":
https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L5040

3) In spec, after VU for VkPresentInfoKHR `VkPresentInfoKHR::pNext` seems to be missing pname: decoration for the pNext

**Comment by oddhack** [comment]
This should all be fixed in the next public update. I've already committed the trivial fixes to our internal tree and am closing this now to get it off the table.

**Comment by krOoze** [comment]
@oddhack reopen? In 1.0.17 1) does not seem to be fixed despite changelog saying so (it is in 1.0-VK_KHR_swapchain so probably a bad merge?), 3) not fixed either (in neither branch).

**Comment by oddhack** [comment]
Fixed AFAICT in 1.0.18
