### ISSUE TITLE
Description of rounding behavior of mipmap dimensions in Images chapter is wrong

### ISSUE THREAD

**Issue by elasota** [KhronosGroup/Vulkan-Docs#2588]
I'm not actually sure if this is a bug in the spec or the validation layers, but given that everything else I can find disagrees with the spec, I think this is a spec bug.

Images chapter specifies ceil rounding for mip dimensions (relevant in cases where a dimension is non-power-of-two):
https://github.com/KhronosGroup/Vulkan-Docs/blob/dad8cec7a33e672d3a575072b75da6261686e2d2/chapters/images.adoc?plain=1#L67
```
  * [eq]#width~level~ = {lceil}width / 2^level^{rceil}#
  * [eq]#height~level~ = {lceil}height / 2^level^{rceil}#
  * [eq]#depth~level~ = {lceil}depth / 2^level^{rceil}#
```
The validation layers round down:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/681e1f4c999d21871be06bea85fe868eda6aeb94/layers/utils/image_utils.cpp#L78

KTX tools round down:
https://github.com/KhronosGroup/KTX-Software/blob/0306d6a614ddde1b88c2a1b7d65186a20cdd4d25/lib/texture1.c#L1117

ARB_texture_non_power_of_two in OpenGL rounds down.  D3D rounds down.  IHV papers suggest downward rounding.

**Comment by HansKristian-Work** [comment]
Indeed. Extremely bizarre oversight.

12.4.3 Image Mip Level Sizing has the proper formulae.

**Comment by elasota** [comment]
Hmm according to that chapter, ceil is used for corner-sampled images, which means the validation layer formula might be wrong for that case?  Time to go test this I guess.

And looks like KTX just doesn't support it.

**Comment by HansKristian-Work** [comment]
Corner sampled is a vendor extension which might not have proper VVL support yet. Don't know the status of that, but corner sampled rounds up, yes.

**Comment by elasota** [comment]
Looks like VVL actually checks for that bit but then uses the wrong rounding anyway, so posted a PR to fix that:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/10844

**Comment by spencer-lunarg** [comment]
Aww, yes using `VK_IMAGE_CREATE_CORNER_SAMPLED_BIT_NV` (`VK_NV_corner_sampled_image`) has VVL supported "added" , but clearly was missing any meaningful test and I regressed it ... thanks @elasota for getting a fix (I am not familiar with the details of this extension)

**Comment by spencer-lunarg** [comment]
We fixed in VVL, @elasota can we close this or is there still more to do?

**Comment by elasota** [comment]
> We fixed in VVL, [@elasota](https://github.com/elasota) can we close this or is there still more to do?

The original problem this issue was reported for is still present: The Images chapter of the spec (as linked in the description of this issue) describes the rounding behavior incorrectly, so I think it either needs to be changed to match 12.4.3 or to reference 12.4.3 or both.

The corner-sampled case is really just an additional problem that was found incidentally while looking at this.

**Comment by oddhack** [comment]
This should be fixed in the 1.4.330 spec update (it will take a little while for this to propagate out to docs.vulkan.org).
