### ISSUE TITLE
VkImageSubresourceRange Valid Usage

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#303]
The Valid Usage requirements for `VkImageSubresourceRange` seem quite under-constrained.

E.g. if I create an image with mipLevels=1, arrayLayers=1, I think these ranges are valid:
- { baseMipLevel=0, levelCount=0, baseArrayLayer=0, layerCount=0 }
- { baseMipLevel=1, levelCount=0, baseArrayLayer=1, layerCount=0 }
- { baseMipLevel=1, levelCount=VK_REMAINING_MIP_LEVELS, baseArrayLayer=1, layerCount=VK_REMAINING_ARRAY_LAYERS }
- { baseMipLevel=100, levelCount=VK_REMAINING_MIP_LEVELS, baseArrayLayer=100, layerCount=VK_REMAINING_ARRAY_LAYERS }

I think it'd be weird and inconsistent if those were intentionally permitted as referring to an empty set of subresources - e.g. you can't have a `VkBufferMemoryBarrier` with size=0, but that would let you have a `VkImageMemoryBarrier` with zero subresources (which would raise questions about how exactly that's meant to behave).

It should probably require that baseMipLevel < mipLevels, and that levelCount > 0 if it's not REMAINING, and similar for layers.

**Comment by philiptaylor** [comment]
The empty set is still a subset of the image's subresources.

**Comment by krOoze** [comment]
^ Yes, but it's possibly not wrong (in contrast to the other variants)

**Comment by oddhack** [comment]
This should be fixed in the 1.0.34 spec update.

**Comment by krOoze** [comment]
@oddhack There is some problem with the fix.

The html output is missing the plus "+" in the "baseMipLevel + levelCount".

I think the "+" at end of the line has special meaning in the asciidoc source.

**Comment by krOoze** [comment]
PS:
also doesn't fix the last two counter-examples (for the cases of `VK_REMAINING*`).

also not sure it should reference the image here (based on the "not neccessarily in this VU, but where the state is known" rule).
