### ISSUE TITLE
Dynamic state (esp. viewport and scissor) handling ambiguous

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#620]
I think the dynamic state is bit underspecified.
Emergent problems from invalid #540.

It is described at the start of Pipeline chapter (1. which is bit unfortunate and many places could use backlinks):

> A pipeline object is bound to the device state in command buffers. Any pipeline object state that is marked as dynamic is not applied to the device state when the pipeline is bound. Dynamic state not set by binding the pipeline object **can** be modified at any time and persists for the lifetime of the command buffer, or until modified by another dynamic state command or another pipeline bind. No state, including dynamic state, is inherited from one command buffer to another. Only dynamic state that is **required** for the operations performed in the command buffer needs to be set. For example, if blending is disabled by the pipeline state then the dynamic color blend constants do not need to be specified in the command buffer, even if this state is marked as dynamic in the pipeline state object. If a new pipeline object is bound with state not marked as dynamic after a previous pipeline object with that same state as dynamic, the new pipeline object state will override the dynamic state. Modifying dynamic state that is not set as dynamic by the pipeline state object will lead to undefined results.

2. It is not quite obvious what the static state viewport pipeline does to the dynamic state. The relevant parts are:

> [...], or **until modified by** another dynamic state command **or another pipeline bind**

> If a new pipeline object is bound with state not marked as dynamic after a previous pipeline object with that same state as dynamic, the new pipeline object state will override the dynamic state.

a) It is not obvious if the new pipeline overwrites the dynamic state with its state.

b) If so, it is not obvious if it changes the dynamic state count or only overwrites that part of the dynamic state array that is within its static count.

c) If not, it is not obvious if previous dynamic state is restored when the static state pipeline is unbound, or if it is trashed (and if it is trashed whole, or only upto the static count).

d) It does not say what happens if new static state pipeline object is bound when **no** pipeline was previously bound.

e) "until modified by [...] another pipeline bind" is highly ambiguous what it means.

3. It is not obvious what happens if dynamic-state pipeline follows another dynamic-state pipeline.
Does it trash elements past the staticly set count?

4.
> Modifying dynamic state that is not set as dynamic by the pipeline state object will lead to undefined results.

As per #379 ambiguous. As per below VU should probably mean "undefined behavior". (Or the VU is wrong.)

5. The VU of e.g. `vkCmdSetViewport` says:

> - The currently bound graphics pipeline **must** have been created with the `VK_DYNAMIC_STATE_VIEWPORT` dynamic state enabled

The dynamic state is per-cmdbuffer. Is it really neccessary to have any pipeline bound at all?

**Comment by oddhack** [comment]
This should be fixed in the 1.1.71 spec update.

**Comment by krOoze** [comment]
Hm, this feels it was unclarified again at some point...
I am still not sure how arrayed dynamic state works, and when and to what degree it gets disturbed by new pipeline.
